DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS wallet;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE wallet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  ticker_symbol TEXT NOT NULL,
  value_bought INTEGER NOT NULL,
  volume_bought FLOAT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);